### ISSUE TITLE
Make snippets globally accessible on a system

### ISSUE THREAD

**Issue by kpinnipa** [jupytercalpoly/jupyterlab-code-snippets#121]
**Is your feature request related to a problem? Please describe.**
Right now snippets are created and saved into a folder that is separate for each directory. This means that when jupyterlab is launched from a different directory it can be hard to access those snippets because they are in a folder in a separate directory. 

**Describe the solution you'd like**
Figure out a way to make snippets available anywhere jupyterlab is launched. This way snippets from other projects can be used in a new workspace without needing to recreate them. This means sending all the snippets created to one location on the user's computer.

**Comment by sntgluca** [comment]
I think this would be great to have, and ideally configurable from JupyterLab's `advanced settings`.

Incidentally I would welcome the possibility to pick from several directories - to allow for instance _personal_ code snippets along with _shared_ code snippets.

That's because I would love to have the possibility to share code snippets to a group of users from a JupyterHub environment.

**Comment by dcervenkov** [comment]
Hi @kpinnipa, any ETA on the release with global snippets?

**Comment by jahn96** [comment]
Hi @dcervenkov,
We are planning to release it sometime this week.
Thank you so much for your interest!

**Comment by dcervenkov** [comment]
@jahn96 that's good to hear. Thank you for the nice plugin!
